name: Build

on:
  #push
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.23.x'

      - name: Install dependencies
        run: go get ./...

      #- name: Tests
      #  run: make test

      - name: Build
        run: make build

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
            name: build-results
            path: bin/ltdav
